import type { Invoice } from "@/types/invoice";

export const mockInvoices: Invoice[] = [
  {
    id: "#RT3080",
    status: "paid",
    createdAt: "2021-08-01",
    paymentDue: "2021-08-19",
    description: "Re-branding design work",
    paymentTerms: 30,
    clientName: "Jensen Huang",
    clientEmail: "jensen@hng.com",
    senderAddress: {
      street: "19 Roadway",
      city: "London",
      postCode: "E1 8LG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "14 Kensington Park",
      city: "London",
      postCode: "SW5 0DH",
      country: "United Kingdom",
    },
    items: [{ name: "Brand guidelines", quantity: 1, price: 1800.9, total: 1800.9 }],
    total: 1800.9,
  },
  {
    id: "#XM9141",
    status: "pending",
    createdAt: "2021-09-04",
    paymentDue: "2021-09-20",
    description: "Landing page design",
    paymentTerms: 30,
    clientName: "Alex Grim",
    clientEmail: "alex@grim.co",
    senderAddress: {
      street: "19 Roadway",
      city: "London",
      postCode: "E1 8LG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "33 Chester Road",
      city: "Manchester",
      postCode: "M1 1AE",
      country: "United Kingdom",
    },
    items: [{ name: "Landing page", quantity: 1, price: 556.0, total: 556.0 }],
    total: 556.0,
  },
  {
    id: "#RG0314",
    status: "paid",
    createdAt: "2021-09-02",
    paymentDue: "2021-10-01",
    description: "Website design and development",
    paymentTerms: 30,
    clientName: "John Morrison",
    clientEmail: "john@morrison.co",
    senderAddress: {
      street: "19 Roadway",
      city: "London",
      postCode: "E1 8LG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "92 Forest Street",
      city: "Bristol",
      postCode: "BS1 4DJ",
      country: "United Kingdom",
    },
    items: [{ name: "Custom website", quantity: 1, price: 14002.33, total: 14002.33 }],
    total: 14002.33,
  },
  {
    id: "#RT2080",
    status: "pending",
    createdAt: "2021-09-08",
    paymentDue: "2021-10-12",
    description: "Logo and brand system",
    paymentTerms: 30,
    clientName: "Alysa Werner",
    clientEmail: "alysa@werner.com",
    senderAddress: {
      street: "19 Roadway",
      city: "London",
      postCode: "E1 8LG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "52 Kingsway",
      city: "London",
      postCode: "WC2B 6NH",
      country: "United Kingdom",
    },
    items: [{ name: "Logo & brand system", quantity: 1, price: 102.04, total: 102.04 }],
    total: 102.04,
  },
  {
    id: "#AA1449",
    status: "pending",
    createdAt: "2021-09-12",
    paymentDue: "2021-10-14",
    description: "Packaging design",
    paymentTerms: 30,
    clientName: "Melisa Clarke",
    clientEmail: "melisa@clarke.io",
    senderAddress: {
      street: "19 Roadway",
      city: "London",
      postCode: "E1 8LG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "4 Heather Lane",
      city: "York",
      postCode: "YO1 8QT",
      country: "United Kingdom",
    },
    items: [{ name: "Packaging mockups", quantity: 1, price: 4032.33, total: 4032.33 }],
    total: 4032.33,
  },
  {
    id: "#TY9141",
    status: "pending",
    createdAt: "2021-09-24",
    paymentDue: "2021-10-31",
    description: "Social media branding kit",
    paymentTerms: 30,
    clientName: "Thomas Wayne",
    clientEmail: "thomas@wayne.org",
    senderAddress: {
      street: "19 Roadway",
      city: "London",
      postCode: "E1 8LG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "66 Grove Road",
      city: "Liverpool",
      postCode: "L8 0RN",
      country: "United Kingdom",
    },
    items: [{ name: "Brand assets", quantity: 1, price: 6155.91, total: 6155.91 }],
    total: 6155.91,
  },
  {
    id: "#FV2353",
    status: "draft",
    createdAt: "2021-10-01",
    paymentDue: "2021-11-12",
    description: "App development kickoff",
    paymentTerms: 30,
    clientName: "Anita Wainwright",
    clientEmail: "anita@wainwright.dev",
    senderAddress: {
      street: "19 Roadway",
      city: "London",
      postCode: "E1 8LG",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "8 Elm Street",
      city: "Leeds",
      postCode: "LS1 4AP",
      country: "United Kingdom",
    },
    items: [{ name: "Project setup", quantity: 1, price: 3102.04, total: 3102.04 }],
    total: 3102.04,
  },
];